[[language]]
name = "python"
file-types = ["py", "pyi"]
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args = [
  "--stdio",
], timeout = 20 }
formatter = { command = "black", args = ["-", "-q"] }
auto-format = true
config = {}
